replicaCount: 1

postgresql:
  fullnameOverride: notification-postgres
  postgresqlUsername: notification-architect
  postgresqlPassword: notification-architect
  postgresqlDatabase: notification-architect
  service:
    type: NodePort
    port: 5434
  persistence: 
    enabled: true
    size: 1Gi
  resources: 
    requests: 
      memory: 256Mi
      cpu: 250m

db: 
  host: "notification-postgres"
  database: "notification-architect"
  username: "notification-architect"
  password: "notification-architect" 
  port: "5434"

metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: false
  hosts:
    - host: arch.homework
      paths: ["/"]