version: '2.0'
services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: architect
      POSTGRES_USER: architect
      POSTGRES_DB: architect