server:
  port: 8000

app:
  database:
    db: ${DB_NAME:architect}
    host: ${DB_HOST:postgres}
    port: ${DB_PORT:5433}
    username: ${DB_USERNAME:architect}
    password: ${DB_PASSWORD:architect}
  internal-services:
    user-service: testrandomtest

spring:
  datasource:
    url: jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.db}
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: org.postgresql.Driver
    platform: postgresql