replicaCount: 1

postgresql:
  fullnameOverride: auth-postgres
  postgresqlUsername: auth-architect
  postgresqlPassword: auth-architect
  postgresqlDatabase: auth-architect
  service:
    type: NodePort
    port: 5433
  persistence: 
    enabled: true
    size: 1Gi
  resources: 
    requests: 
      memory: 256Mi
      cpu: 250m

db: 
  host: "auth-postgres"
  database: "auth-architect"
  username: "auth-architect"
  password: "auth-architect" 
  port: "5433"

metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: false
  hosts:
    - host: arch.homework
      paths: ["/auth"]