apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: auth-app
  template: 
    metadata:
      labels: 
        app: auth-app
    spec: 
      containers: 
      - name: auth-backend
        image: allash/auth-service:v9
        ports: 
        - name: web
          containerPort: 8000
        livenessProbe:
          httpGet:
            port: 8000
            path: /
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8000
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
        env: 
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: database
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: port
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: password