version: '2.0'
services:
  db:
    container_name: auth_postgres
    image: postgres:11
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: architect
      POSTGRES_USER: architect
      POSTGRES_DB: architect