replicaCount: 1

postgresql:
  fullnameOverride: postgres
  postgresqlUsername: architect
  postgresqlPassword: architect
  postgresqlDatabase: architect
  service:
    type: NodePort
    port: 5432
  persistence: 
    enabled: true
    size: 1Gi
  resources: 
    requests: 
      memory: 256Mi
      cpu: 250m

db: 
  host: "postgres"
  database: "architect"
  username: "architect"
  password: "architect" 
  port: "5432"