version: '2.0'
services:
  db:
    container_name: user_postgres
    image: postgres:11
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: architect
      POSTGRES_USER: architect
      POSTGRES_DB: architect