---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-app
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32081
      targetPort: 8000
      name: "http" 
  selector:
    app: proxy-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-app
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: proxy-app
      version: "1"
  template:
    metadata:
      labels:
        app: proxy-app
        version: "1"
    spec:
      containers:
        - name: proxy-app
          image: allash/architect-backend-istio:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000